name: azure bicep resource deletion

on:
  workflow_dispatch

jobs:
  delete:
    name: 'delete bicep resource'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Check if directory exists
        run: ls ${{ github.workspace }}/src/bicep

      - name: Validate Bicep Script using What-If
        working-directory: ${{github.workspace}}/src/bicep
        run: az deployment group what-if --resource-group Abhijitchaudhari7898 --template-file ./main.bicep --parameters @mainA.parameters.json

      - name: List and Delete All Resources in Resource Group
        run: |
          # List and delete resources in specific order to handle dependencies
          resource_types_to_delete_first=(
            "Microsoft.Network/networkInterfaces"
            "Microsoft.Compute/virtualMachines"
            "Microsoft.Network/publicIPAddresses"
          )
          
          for resource_type in "${resource_types_to_delete_first[@]}"; do
            resources=$(az resource list --resource-group Abhijitchaudhari7898 --resource-type $resource_type --query "[].id" -o tsv)
            for resource in $resources; do
              echo "Deleting resource: $resource"
              if ! az resource delete --ids $resource --verbose; then
                echo "Failed to delete resource: $resource"
              fi
            done
          done
          
          # Now delete the remaining resources
          resources=$(az resource list --resource-group Abhijitchaudhari7898 --query "[].id" -o tsv)
          for resource in $resources; do
            echo "Deleting resource: $resource"
            if ! az resource delete --ids $resource --verbose; then
              echo "Failed to delete resource: $resource"
            fi
          done


          